/**
 *
 * $Id$
 */
package useCase.validation;

import org.eclipse.emf.common.util.EList;

import useCase.Actor;
import useCase.UseCase;

/**
 * A sample validator interface for {@link useCase.Specification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SpecificationValidator {
	boolean validate();

	boolean validateOwnedUseCase(EList<UseCase> value);
	boolean validateOwnedActor(EList<Actor> value);
	boolean validateOwnedProcess(EList<useCase.Process> value);
}
