/**
 *
 * $Id$
 */
package useCase.validation;

import org.eclipse.emf.common.util.EList;

import useCase.Actor;
import useCase.Interest;

/**
 * A sample validator interface for {@link useCase.UseCase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UseCaseValidator {
	boolean validate();

	boolean validatePrimaryActor(Actor value);
	boolean validateOwnedStakeholderInterest(EList<Interest> value);
	boolean validateMainFlow(useCase.Process value);
	boolean validateAlternativeFlows(EList<useCase.Process> value);
}
