/**
 *
 * $Id$
 */
package DocModel.validation;

import DocModel.Paragraph;
import DocModel.Part;

import org.apache.poi.xwpf.usermodel.XWPFParagraph;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link DocModel.Paragraph}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParagraphValidator {
	boolean validate();

	boolean validateOwnedNode(EList<Paragraph> value);
	boolean validateParentNode(Paragraph value);
	boolean validateParagraph(XWPFParagraph value);
	boolean validateOwnedPart(EList<Part> value);
	boolean validateFirstPart(Part value);
}
