/**
 *
 * $Id$
 */
package DocModel.validation;

import DocModel.Node;

import org.apache.poi.xwpf.usermodel.XWPFRun;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link DocModel.Node}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeValidator {
	boolean validate();

	boolean validateOwnedNode(EList<Node> value);
	boolean validateNextNode(Node value);
	boolean validatePrevNode(Node value);
	boolean validateParentNode(Node value);
	boolean validateAggregatedRun(EList<XWPFRun> value);
}
