/**
 *
 * $Id$
 */
package DocModel.validation;

import DocModel.Node;
import DocModel.Part;

import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link DocModel.Node}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeValidator {
	boolean validate();

	boolean validateRawText(String value);
	boolean validateAggregatedRun(XWPFRun value);
	boolean validateOwnedNode(EList<Node> value);
	boolean validateParentNode(Node value);
	boolean validateParagraph(EList<XWPFParagraph> value);
	boolean validateOwnedPart(EList<Part> value);
	boolean validateFirstPart(Part value);
}
